#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

APP_NAME="Leakmax"
APP_UI_TEST_SCHEME="LeakmaxUITests"
APP_RUNNER_NAME="$APP_UI_TEST_SCHEME-Runner"
APP_DIR="$SCRIPT_DIR/app"
APP_WORKSPACE="$APP_DIR/Leakmax.xcworkspace"
APP_UI_TEST_PRINCIPAL_CLASS="PrincipalClass"
APP_UI_TEST_PRINCIPAL_CLASS_FILE="$APP_DIR/LeakmaxUITests/Support/$APP_UI_TEST_PRINCIPAL_CLASS.swift"
APP_UI_TEST_NAMES=( \
 	"$APP_UI_TEST_SCHEME/NumberGeneratorUITests" \
)
SIMULATOR_NAME="" # Here fill your simulator name

if [ -z "$SIMULATOR_NAME" ]
then
      echo 'Error: Please, fill name of simulator in `SIMULATOR_NAME` variable inside `check_memory_leaks` script.'
      exit 1
fi

bash "$SCRIPT_DIR/memory-leak-tester/start"    \
        "$APP_NAME" \
        "$APP_RUNNER_NAME" \
        "$APP_WORKSPACE" \
        "$APP_UI_TEST_SCHEME" \
        ".memory-leak-tester-reports" \
        ".memory-leak-tester-build" \
        "$SIMULATOR_NAME" \
        "$APP_UI_TEST_PRINCIPAL_CLASS_FILE" \
        "$APP_UI_TEST_PRINCIPAL_CLASS" \
        "$APP_UI_TEST_NAMES"
